<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**

##CS6462 - PROBABILISTIC AND EXPLAINABLE AI 
##SEM2 2021/2

###CS6462_Etivity_2a_solution

###Instructor: Enrique Naredo

Copyright (C) 2022 - All rights reserved, do not copy or distribute without permission of the author.

## Libraries

In [ ]:
import seaborn as sns

##Regression

Apply the Bayesian Linear Models on the regression 'tips' dataset using the code from the Example-3.

**Predict for total bills**

**Comparison**
Compare against the following methods
* Siple Linear estimation form Lab 4.1
* LinearRegression from Sklearn
* Bayesian Linear Regression

**Note**: Use as much as possible what you have learned from the Labs 4.1 to 4.3

In [33]:
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##Classification

Apply the Generalized Linear Models on the classification 'diamonds' dataset using the code from the Example-7.

**Classes:**

* Ideal:  21551
* Premium:      13791
* Very Good:    12082
* Good:          4906
* Fair:          1610

**Comparison**
Compare against the following methods
* Logistic Regresion
* Random Forests
* Gradient Boosting Classifier

**Note**: Use as much as possible what you have learned from the Labs 4.4 to 4.7

In [32]:
diamonds = sns.load_dataset('diamonds')
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75